### ISSUE TITLE
Interactive HTML output plots via Plotly backend of Plots.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [mpastell/Weave.jl#186]
Plots.jl's Plotly backend creates interactive HTML plots. It would be nice if, when using the HTML render, if the Weave.jl output could have that interactive form.

**Comment by mpastell** [comment]
You already can, this should just work:

```julia
using Plots
plotly()
plot(randn(100))
```

**Comment by ChrisRackauckas** [comment]
Huh, when I tried back then it did, but it's working now.

**Comment by josephmarturano** [comment]
I apologize for re-opening this 5 month old issue, but I am having trouble generating HTML output with interactive plots. I would like to get this working because for me interactive plots bring scientific reports to the next level, beyond say MS Word with static plots. Could someone please provide full instructions for generating interactive plots in a Weave HTML output? I tried a few combinations on Windows 7 using VS Code.

**Attempt #1**
In the editor, I entered and ran the following:
```
using Plots
plotly()
plot(randn(100))
```
I save the file as "test_interactive_weave.jl". Then in the VS Code Julia console, I entered the following Weave command:

`using Weave; weave("C:/Julia/test_interactive_weave.jl", out_path=:doc, doctype="md2html")`

But in the rendered HTML file, I see the code but instead of a plot, I see red text that reads:

> ERROR: only png or svg allowed. got: :html

**Attempt #2**
Next, I tried changing "plotly()" to "plotlyjs()", but after entering the same Weave command, in the rendered HTML output I see the following red text:

> ERROR: UndefVarError: data not defined

**Attempt #3**
So then I tried changing the doctype to "pandoctohtml", i.e., the following Weave command:

`using Weave; weave("C:/Julia/test_interactive_weave.jl", out_path=:doc, doctype="pandoc2html")`

When I use plotly() as the backend and pandoctohtml, I see the "got :html" error as before:

> ERROR: only png or svg allowed. got: :html

**Attempt #4**
And when I use plotlyjs() and pandoctohtml, I see the same "data not defined" error:

> ERROR: UndefVarError: data not defined
