### ISSUE TITLE
Comparison with knitr?

### ISSUE THREAD

**Issue by sje30** [mpastell/Weave.jl#24]
Hi, 
[apologies in advance -- this is not a technical "issue"]

Thanks very much for providing this package, I am testing it out now.  I just wondered whether you had considered extending knitr in R to handle julia code, rather than reimplementing a lot of knit features in julia?  Knitr is a great system, much better than the original Sweave in R.  e.g. caching of outputs is a great concept.  I appreciate that its not ideal to use an R package from Julia.

Good luck with its development!

**Comment by mpastell** [comment]
Hi,
I didn't really consider extending Knirt, because I don't use that much R nowadays. There is the runr https://github.com/yihui/runr package which enables calling Julia from Knitr. 

I did send an email to knirt mailing list if anyone would be interested collaboration
https://groups.google.com/forum/#!searchin/knitr/julia/knitr/F78PBMIamwk/X-d-zUhrdrkJ. 

If you'd like to work on extending runr, then I think you can benefit from some of the functionality on Weave and I could collaborate on that on the Julia side.  

And if there is a specific feature from Knitr that you'd like to see do open an issue.

**Comment by sje30** [comment]
Thanks!  I'll check out runr again (I did a long time ago), and weigh up the pros/cons of which approach to take.

**Comment by mpastell** [comment]
And thanks for the question, I welcome non-technical issues as well and it seems that a mailing list won't make sense at this point. I opened issue #25 to remind myself to work on caching.
