### ISSUE TITLE
weave seems to hang at one point for me

### ISSUE THREAD

**Issue by dmbates** [mpastell/Weave.jl#53]
I am using Weave version 0.1.2 under Julia 0.5.0 to generate documentation for the [`MixedModels`](https://github.com/dmbates/MixedModels.jl) package.  The file `docs/src/man/bootstrap.jmd` is the source.  If I run the chunks separately, it takes about 8 seconds to execute chunk 7.  When I try to weave the file it hangs at chunk 7, the call to `bootstrap!`.

**Comment by dmbates** [comment]
The issue seems to be related to time required for evaluation.  If I change the number of bootstrap replicates from 100,000 to 1,000 in the call to `bootstrap!` the run succeeds.

**Comment by mpastell** [comment]
Thanks for letting me know and sorry for not being more responsive. I'll look into it when I find some time.

**Comment by mpastell** [comment]
The issue seems to be related to using term true which causes the whole result to be displayed. Printing out the result is clearly a bug as the semicolon doesn't suppress output.

When I remove `term=true` from options the `bootstrap!` call doesn't hang anymore.

Also Weave hanging when a chunk produces too much output is a bug which I need investigate further.

**Comment by mpastell** [comment]
The bug for semicolons in `term=true` is now fixed and so your document now works. It seems that I can't fix the more general issue of Weave hanging when there is too much output.
