### ISSUE TITLE
Review for JOSS

### ISSUE THREAD

**Issue by vchuravy** [mpastell/Weave.jl#85]
I just started my review for JOSS (https://github.com/openjournals/joss-reviews/issues/204) and I will note down issues as I encounter them:

- [x] I get warnings for Base methods that are overwritten on both 0.5 and 0.6? Is this necessary? (`latex` and `latexinline`)
- [x] The copyright notice in LICENSE.md should be updated from `Copyright (c) 2014: Matti Pastell.` to `Copyright (c) 2014-2017: Matti Pastell and other contributors.`
- [x] There are a bunch of deprecation warnings for Julia v0.6 and it would be great if these could be addressed.
- [x] The optional dependencies for the examples in https://github.com/mpastell/Weave.jl#usage e.g. `Gadlfy`, `Cairo`, `Fontconfig` should be mentioned.
- [x] I also get the following warning on v0.5 that should be fixed.
```
WARNING: eval from module Base to Weave:    
Expr(:->, :x, Expr(:block, Expr(:line, 554, :/home/wallnuss/.julia/v0.5/Documenter/src/DocChecks.jl)::Any, Expr(:block, :_ = :have_color, Expr(:global, :have_color = :x)::Any, :_)::Any)::Any)::Any
  ** incremental compilation may be broken for this module **
```

**Comment by mpastell** [comment]
Hi,
Thanks for being so quick to start and for the remarks. A lot of the issues are already fixed in current Weave master. Here are few first responses:

1. Base.markdown methods need to be overwritten for 0.5, but not 0.6 (fixed in https://github.com/JuliaLang/julia/pull/19842 and https://github.com/JuliaLang/julia/pull/19832). I don't get any warnings with version 0.6.0-pre.alpha.34.
2. I've started fixing deprecation warnings in current master. I think all of the warnings from Weave are fixed, but most of the depencies haven't been updated (or at least not tagged yet). I will try to get a "warning free" version released when Julia 0.6 is released.
3. The warning about precompilation has appeared after last release and has been fixed current in master by setting `__precompile__(false)`.

**Comment by mpastell** [comment]
I just updated the license as well.

**Comment by vchuravy** [comment]
Ok that sounds good once I am done with my review it would be great if you could release a new version.

**Comment by mpastell** [comment]
I have now added the info about depencies for examples to readme and docs. Are there any further issues? 

I will tag a new version v0.4.1 after the review is finished.

**Comment by vchuravy** [comment]
No everything is fine by me.

**Comment by mpastell** [comment]
Many thanks for the review! I have now tagged v0.4.1 with these corrections and few other bug fixes.

**Comment by vchuravy** [comment]
One more thing I just noticed. The proper citation info for the Julia paper is
```
@article{doi:10.1137/141000671,
author = {Jeff Bezanson and Alan Edelman and Stefan Karpinski and Viral B. Shah},
title = {Julia: A Fresh Approach to Numerical Computing},
journal = {SIAM Review},
volume = {59},
number = {1},
pages = {65-98},
year = {2017},
doi = {10.1137/141000671},
}
```

after: http://epubs.siam.org/doi/10.1137/141000671

**Comment by mpastell** [comment]
Thanks for letting me know, I fixed it.
